version: '3.8'

services:
  db:
    image: postgres:15
    container_name: subscription_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: subscription_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: subscription_web
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: ["sh", "./entrypoint.sh"]

  celery:
    build: .
    container_name: subscription_celery
    command: celery -A trackerapp worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: subscription_beat
    command: celery -A trackerapp beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app

volumes:
  postgres_data:
