name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    - name: Run tests with coverage
      run: |
        cd subscription_tracker
        coverage run --source=. -m pytest
        coverage report
      env:
        DJANGO_SETTINGS_MODULE: subscription_tracker.settings
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_NAME: github_actions
